name: Platformatory
title: Platformatory | Cloud native engineering studio
description: Thoughts on Platform Engineering, Modernization, DevSecvOps & Reliability Engineering 
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: hello@platformatory.com
#disqus_username: disqus_username
